# Generated by Django 3.2.25 on 2024-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndikatorBruttoinlandsprodukt',
            fields=[
                ('lfd_nr', models.IntegerField(primary_key=True, serialize=False)),
                ('eu_code', models.CharField(max_length=5)),
                ('regional_schluessel', models.CharField(max_length=5)),
                ('land', models.CharField(max_length=2)),
                ('nuts_1', models.IntegerField(null=True)),
                ('nuts_2', models.IntegerField(null=True)),
                ('nuts_3', models.IntegerField(null=True)),
                ('gebietseinheit', models.CharField(max_length=50)),
                ('jahr_1992', models.BigIntegerField(null=True)),
                ('jahr_1994', models.BigIntegerField(null=True)),
                ('jahr_1995', models.BigIntegerField(null=True)),
                ('jahr_1996', models.BigIntegerField(null=True)),
                ('jahr_1997', models.BigIntegerField(null=True)),
                ('jahr_1998', models.BigIntegerField(null=True)),
                ('jahr_1999', models.BigIntegerField(null=True)),
                ('jahr_2000', models.BigIntegerField(null=True)),
                ('jahr_2001', models.BigIntegerField(null=True)),
                ('jahr_2002', models.BigIntegerField(null=True)),
                ('jahr_2003', models.BigIntegerField(null=True)),
                ('jahr_2004', models.BigIntegerField(null=True)),
                ('jahr_2005', models.BigIntegerField(null=True)),
                ('jahr_2006', models.BigIntegerField(null=True)),
                ('jahr_2007', models.BigIntegerField(null=True)),
                ('jahr_2008', models.BigIntegerField(null=True)),
                ('jahr_2009', models.BigIntegerField(null=True)),
                ('jahr_2010', models.BigIntegerField(null=True)),
                ('jahr_2011', models.BigIntegerField(null=True)),
                ('jahr_2012', models.BigIntegerField(null=True)),
                ('jahr_2013', models.BigIntegerField(null=True)),
                ('jahr_2014', models.BigIntegerField(null=True)),
                ('jahr_2015', models.BigIntegerField(null=True)),
                ('jahr_2016', models.BigIntegerField(null=True)),
                ('jahr_2017', models.BigIntegerField(null=True)),
                ('jahr_2018', models.BigIntegerField(null=True)),
                ('jahr_2019', models.BigIntegerField(null=True)),
                ('jahr_2020', models.BigIntegerField(null=True)),
                ('jahr_2021', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'indikator_bruttoinlandsprodukt',
            },
        ),
        migrations.CreateModel(
            name='IndikatorErwerbstaetige',
            fields=[
                ('lfd_nr', models.IntegerField(primary_key=True, serialize=False)),
                ('eu_code', models.CharField(max_length=5)),
                ('regional_schluessel', models.CharField(max_length=5)),
                ('land', models.CharField(max_length=2)),
                ('nuts_1', models.IntegerField(null=True)),
                ('nuts_2', models.IntegerField(null=True)),
                ('nuts_3', models.IntegerField(null=True)),
                ('gebietseinheit', models.CharField(max_length=50)),
                ('jahr_1992', models.FloatField(null=True)),
                ('jahr_1994', models.FloatField(null=True)),
                ('jahr_1995', models.FloatField(null=True)),
                ('jahr_1996', models.FloatField(null=True)),
                ('jahr_1997', models.FloatField(null=True)),
                ('jahr_1998', models.FloatField(null=True)),
                ('jahr_1999', models.FloatField(null=True)),
                ('jahr_2000', models.FloatField(null=True)),
                ('jahr_2001', models.FloatField(null=True)),
                ('jahr_2002', models.FloatField(null=True)),
                ('jahr_2003', models.FloatField(null=True)),
                ('jahr_2004', models.FloatField(null=True)),
                ('jahr_2005', models.FloatField(null=True)),
                ('jahr_2006', models.FloatField(null=True)),
                ('jahr_2007', models.FloatField(null=True)),
                ('jahr_2008', models.FloatField(null=True)),
                ('jahr_2009', models.FloatField(null=True)),
                ('jahr_2010', models.FloatField(null=True)),
                ('jahr_2011', models.FloatField(null=True)),
                ('jahr_2012', models.FloatField(null=True)),
                ('jahr_2013', models.FloatField(null=True)),
                ('jahr_2014', models.FloatField(null=True)),
                ('jahr_2015', models.FloatField(null=True)),
                ('jahr_2016', models.FloatField(null=True)),
                ('jahr_2017', models.FloatField(null=True)),
                ('jahr_2018', models.FloatField(null=True)),
                ('jahr_2019', models.FloatField(null=True)),
                ('jahr_2020', models.FloatField(null=True)),
                ('jahr_2021', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'indikator_erwerbstaetige',
            },
        ),
    ]
