# Generated by Django 3.2.25 on 2024-05-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIndikator',
            fields=[
                ('lfd_nr', models.IntegerField(primary_key=True, serialize=False)),
                ('eu_code', models.CharField(max_length=5)),
                ('regional_schluessel', models.CharField(max_length=5)),
                ('land', models.CharField(max_length=2)),
                ('nuts_1', models.IntegerField(null=True)),
                ('nuts_2', models.IntegerField(null=True)),
                ('nuts_3', models.IntegerField(null=True)),
                ('gebietseinheit', models.CharField(max_length=50)),
                ('jahr_1992', models.FloatField(null=True)),
                ('jahr_1994', models.FloatField(null=True)),
                ('jahr_1995', models.FloatField(null=True)),
                ('jahr_1996', models.FloatField(null=True)),
                ('jahr_1997', models.FloatField(null=True)),
                ('jahr_1998', models.FloatField(null=True)),
                ('jahr_1999', models.FloatField(null=True)),
                ('jahr_2000', models.FloatField(null=True)),
                ('jahr_2001', models.FloatField(null=True)),
                ('jahr_2002', models.FloatField(null=True)),
                ('jahr_2003', models.FloatField(null=True)),
                ('jahr_2004', models.FloatField(null=True)),
                ('jahr_2005', models.FloatField(null=True)),
                ('jahr_2006', models.FloatField(null=True)),
                ('jahr_2007', models.FloatField(null=True)),
                ('jahr_2008', models.FloatField(null=True)),
                ('jahr_2009', models.FloatField(null=True)),
                ('jahr_2010', models.FloatField(null=True)),
                ('jahr_2011', models.FloatField(null=True)),
                ('jahr_2012', models.FloatField(null=True)),
                ('jahr_2013', models.FloatField(null=True)),
                ('jahr_2014', models.FloatField(null=True)),
                ('jahr_2015', models.FloatField(null=True)),
                ('jahr_2016', models.FloatField(null=True)),
                ('jahr_2017', models.FloatField(null=True)),
                ('jahr_2018', models.FloatField(null=True)),
                ('jahr_2019', models.FloatField(null=True)),
                ('jahr_2020', models.FloatField(null=True)),
                ('jahr_2021', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndikatorBruttoinlandsprodukt',
            fields=[
                ('baseindikator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseindikator')),
            ],
            options={
                'db_table': 'indikator_bruttoinlandsprodukt',
            },
            bases=('core.baseindikator',),
        ),
        migrations.CreateModel(
            name='IndikatorErwerbstaetige',
            fields=[
                ('baseindikator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseindikator')),
            ],
            options={
                'db_table': 'indikator_erwerbstaetige',
            },
            bases=('core.baseindikator',),
        ),
    ]
