# Generated by Django 3.2.25 on 2024-05-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.TextField()),
                ('herausgegeben_vom', models.TextField()),
                ('herstellung_und_redaktion', models.TextField()),
                ('erscheinungs_folge', models.CharField(default='jährlich', max_length=10)),
                ('erschienen_im', models.CharField(max_length=10)),
                ('berechnungsstand_information', models.TextField()),
            ],
        ),
    ]
